In [1]:

import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
def objective(trial, classifier="SVC"):
    iris = sklearn.datasets.load_iris()
    x, y = iris.data, iris.target

    classifier_name = trial.suggest_categorical("classifier", [classifier])

    if classifier_name == "SVC":
        svc_c = trial.suggest_float("svc_c", 1e-10, 1e10, log=True)
        kernel = trial.suggest_categorical("kernel", ["linear", "poly", "rbf"])
        gama = trial.suggest_categorical("gamma", ["auto", "scale"])

        classifier_obj = sklearn.svm.SVC(kernel=kernel,C=svc_c, gamma="auto")

    else:
        rf_max_depth = trial.suggest_int("rf_max_depth", 2, 32, log=True)
        classifier_obj = sklearn.ensemble.RandomForestClassifier(
            max_depth=rf_max_depth, n_estimators=10
        )

    score = sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3)

    accuracy = score.mean()

    return accuracy

In [10]:

if __name__ == "__main__":
    svc = optuna.create_study(direction="maximize")
    svc.optimize(lambda trial: objective(trial, "SVC"), n_trials=200)
    print(svc.best_trial)

    rf = optuna.create_study(direction="maximize")
    rf.optimize(lambda trial: objective(trial, "RandomForest"), n_trials=200)
    print(rf.best_trial)

[I 2025-03-14 15:02:11,017] A new study created in memory with name: no-name-3ad7a2c5-23c1-4469-a12b-d813763b1757
[I 2025-03-14 15:02:12,290] Trial 0 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 10.38785928077744}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,308] Trial 1 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.2965926336515552}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,337] Trial 2 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 3.050621743803843e-10}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,352] Trial 3 finished with value: 0.7466666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.0257633563183565}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,366] Trial 4 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 2.244751168709498}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,381] Trial 5 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.2729821757188027}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,395] Trial 6 finished with value: 0.9466666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 424.48258155361856}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,410] Trial 7 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 10133656.505417272}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,424] Trial 8 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 1670.988520545541}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,438] Trial 9 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 125960185.52118886}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,457] Trial 10 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 1.1895329896847937e-06}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,475] Trial 11 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 7.926421780354292e-05}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,492] Trial 12 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 21742.169272649837}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,520] Trial 13 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.001489687715810481}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,550] Trial 14 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 241639.70313482062}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,569] Trial 15 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 14.931566674703417}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,587] Trial 16 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 98.96847574704206}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,605] Trial 17 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 6.847146027633831e-07}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,623] Trial 18 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 9395943546.284142}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,640] Trial 19 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.0033102210761392723}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,658] Trial 20 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 1124940.0771347003}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,675] Trial 21 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 10.856196902915288}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,694] Trial 22 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 30.412902855420732}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,711] Trial 23 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 0.09849851065988706}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,729] Trial 24 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 12661.691725541414}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,762] Trial 25 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 28.490603831177857}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,789] Trial 26 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 3.846168220824176e-05}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,814] Trial 27 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 5040.026842420743}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,831] Trial 28 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 0.07327747757859267}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,848] Trial 29 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.6168189272117321}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,865] Trial 30 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 25.719293688142642}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,882] Trial 31 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 7.507845536539972}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,900] Trial 32 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 2.155893217561664}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,918] Trial 33 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.0031577207033917985}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,935] Trial 34 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 142.70532216592076}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,953] Trial 35 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 2.9208946098990407}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,971] Trial 36 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 56039.619002482796}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:12,993] Trial 37 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 5.125411300718158e-10}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,031] Trial 38 finished with value: 0.9533333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 500.0730707780865}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,089] Trial 39 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.16224651482699076}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,126] Trial 40 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 5.810917149535672}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,145] Trial 41 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 11.102285857462595}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,163] Trial 42 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 624.2846938046926}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,181] Trial 43 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 5.316760511625507}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,199] Trial 44 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.015613069520400136}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,217] Trial 45 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.48985195208366017}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,234] Trial 46 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 1911.5932256433748}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,252] Trial 47 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.0003736494236693953}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,270] Trial 48 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.012075779463117187}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,306] Trial 49 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 248.7810639401762}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,325] Trial 50 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 148886.86137207304}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,346] Trial 51 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.650765729199863}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,364] Trial 52 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 6.452827670007962}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,381] Trial 53 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 8.502520729849648}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,399] Trial 54 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 71.60569810033863}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,418] Trial 55 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.36286655163980847}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,436] Trial 56 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 2684.5184058603722}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,453] Trial 57 finished with value: 0.7666666666666666 and parameters: {'classifier': 'SVC', 'svc_c': 0.034040605114910694}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,476] Trial 58 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 2.8219002415669268}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,502] Trial 59 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 2789061.5749556124}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,521] Trial 60 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 103.00809517634109}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,539] Trial 61 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 13.479694406637059}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,558] Trial 62 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 8.595265383633706}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,575] Trial 63 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.4651007755748814}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,594] Trial 64 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 5.362599492847345}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,613] Trial 65 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 10999.364066093478}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,631] Trial 66 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 56.489322788046806}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,649] Trial 67 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 0.08625876620649156}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,667] Trial 68 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 695.1494731664123}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,684] Trial 69 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.2908337068606535}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,702] Trial 70 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 36.837271313191366}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,721] Trial 71 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 9.057540184524443}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,738] Trial 72 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 7.41166805916061}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,758] Trial 73 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.19786697528143166}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,779] Trial 74 finished with value: 0.9466666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 195.16375353672495}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,798] Trial 75 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.3225927788867289}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,816] Trial 76 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 26.316310406545547}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,833] Trial 77 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.006210801333450661}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,851] Trial 78 finished with value: 0.8799999999999999 and parameters: {'classifier': 'SVC', 'svc_c': 0.04118869896814577}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,869] Trial 79 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 1140.6523599005359}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,886] Trial 80 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 78399941.64416957}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,904] Trial 81 finished with value: 0.98 and parameters: {'classifier': 'SVC', 'svc_c': 7.427793863073398}. Best is trial 0 with value: 0.98.
[I 2025-03-14 15:02:13,921] Trial 82 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 3.7665191665315145}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:13,939] Trial 83 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.8158704889100842}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:13,956] Trial 84 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 114.93048253236074}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:13,974] Trial 85 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 3.8229146906724343}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:13,991] Trial 86 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.18266761708567203}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,008] Trial 87 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 3.0491057963208594}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,026] Trial 88 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 0.0009022217566036269}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,044] Trial 89 finished with value: 0.9466666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 366.26107725797533}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,061] Trial 90 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 29.119269509641818}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,080] Trial 91 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 3.084118784245768}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,097] Trial 92 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 14.576691689686497}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,116] Trial 93 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.4669933313030953}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,133] Trial 94 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 64.65615254233572}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,151] Trial 95 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 5405.614462685158}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,170] Trial 96 finished with value: 0.32 and parameters: {'classifier': 'SVC', 'svc_c': 1.3653086552966084e-09}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,187] Trial 97 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 1.4764611156180913}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,205] Trial 98 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 233.42340224010255}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,222] Trial 99 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 0.239444700567389}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,240] Trial 100 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 4.4348803808337}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,258] Trial 101 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 3.703930432903458}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,275] Trial 102 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 4.067043301382179}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,293] Trial 103 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.691978922155311}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,310] Trial 104 finished with value: 0.94 and parameters: {'classifier': 'SVC', 'svc_c': 0.06682767979141015}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,328] Trial 105 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 22.13616407357033}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,345] Trial 106 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 3.951731298269929}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,365] Trial 107 finished with value: 0.9733333333333333 and parameters: {'classifier': 'SVC', 'svc_c': 2.5222214703269197}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,384] Trial 108 finished with value: 0.96 and parameters: {'classifier': 'SVC', 'svc_c': 53.91754194502776}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,402] Trial 109 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 16.93171465515498}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,420] Trial 110 finished with value: 0.9666666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 0.8674287613272518}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,438] Trial 111 finished with value: 0.9866666666666667 and parameters: {'classifier': 'SVC', 'svc_c': 3.7436624921753467}. Best is trial 82 with value: 0.9866666666666667.
[I 2025-03-14 15:02:14,456] Trial 112 finished with value: 0.48666666666666664 and parameters: {'classifier': 'SVC', 'svc_c': 0.018808747558055235}. Best is trial 82 with value: 0.9866666666666667.

FrozenTrial(number=82, state=1, values=[0.9866666666666667], datetime_start=datetime.datetime(2025, 3, 14, 15, 2, 13, 904777), datetime_complete=datetime.datetime(2025, 3, 14, 15, 2, 13, 921580), params={'classifier': 'SVC', 'svc_c': 3.7665191665315145}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'classifier': CategoricalDistribution(choices=('SVC',)), 'svc_c': FloatDistribution(high=10000000000.0, log=True, low=1e-10, step=None)}, trial_id=82, value=None)

[I 2025-03-14 15:02:16,394] Trial 2 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 12}. Best is trial 0 with value: 0.96.
[I 2025-03-14 15:02:16,442] Trial 3 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 17}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,489] Trial 4 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,535] Trial 5 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,582] Trial 6 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,638] Trial 7 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 21}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,686] Trial 8 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,733] Trial 9 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 10}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,783] Trial 10 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 27}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,833] Trial 11 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,883] Trial 12 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,933] Trial 13 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 17}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:16,982] Trial 14 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,032] Trial 15 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 15}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,080] Trial 16 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,130] Trial 17 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 7}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,207] Trial 18 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 30}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,258] Trial 19 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,309] Trial 20 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,360] Trial 21 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,413] Trial 22 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,462] Trial 23 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 9}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,511] Trial 24 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,570] Trial 25 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,627] Trial 26 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,677] Trial 27 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 20}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,727] Trial 28 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 12}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,776] Trial 29 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,837] Trial 30 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,917] Trial 31 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:17,968] Trial 32 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,018] Trial 33 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 7}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,068] Trial 34 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,117] Trial 35 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 11}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,166] Trial 36 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 8}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,216] Trial 37 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,265] Trial 38 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,314] Trial 39 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,364] Trial 40 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 15}. Best is trial 3 with value: 0.9666666666666667.
[I 2025-03-14 15:02:18,434] Trial 41 finished with value: 0.9733333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,489] Trial 42 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,556] Trial 43 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,626] Trial 44 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 22}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,676] Trial 45 finished with value: 0.9733333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,726] Trial 46 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,787] Trial 47 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,837] Trial 48 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 26}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,887] Trial 49 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:18,938] Trial 50 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 14}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,001] Trial 51 finished with value: 0.94 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,057] Trial 52 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,108] Trial 53 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 9}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,158] Trial 54 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 2}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,220] Trial 55 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,277] Trial 56 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,327] Trial 57 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,377] Trial 58 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 32}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,429] Trial 59 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,479] Trial 60 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 8}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,529] Trial 61 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,578] Trial 62 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,629] Trial 63 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,680] Trial 64 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 20}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,730] Trial 65 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,781] Trial 66 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 7}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,831] Trial 67 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,880] Trial 68 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 17}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,930] Trial 69 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 13}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:19,981] Trial 70 finished with value: 0.94 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 9}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,031] Trial 71 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 25}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,081] Trial 72 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 18}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,132] Trial 73 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 24}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,182] Trial 74 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 22}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,232] Trial 75 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 29}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,283] Trial 76 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 18}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,334] Trial 77 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 23}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,384] Trial 78 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 21}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,435] Trial 79 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 5}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,489] Trial 80 finished with value: 0.94 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 11}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,541] Trial 81 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 28}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,603] Trial 82 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 26}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,652] Trial 83 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 26}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,706] Trial 84 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 16}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,757] Trial 85 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 24}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,810] Trial 86 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 32}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,861] Trial 87 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 20}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,911] Trial 88 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:20,961] Trial 89 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 30}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,011] Trial 90 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 22}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,061] Trial 91 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 19}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,111] Trial 92 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 15}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,161] Trial 93 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 13}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,212] Trial 94 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 9}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,272] Trial 95 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 27}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,332] Trial 96 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 8}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,384] Trial 97 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 10}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,435] Trial 98 finished with value: 0.9466666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 11}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,495] Trial 99 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 7}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,547] Trial 100 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 16}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,598] Trial 101 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,648] Trial 102 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,699] Trial 103 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 4}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,751] Trial 104 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 22}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,803] Trial 105 finished with value: 0.9666666666666667 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 6}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,854] Trial 106 finished with value: 0.9533333333333333 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 3}. Best is trial 41 with value: 0.9733333333333333.
[I 2025-03-14 15:02:21,905] Trial 107 finished with value: 0.96 and parameters: {'classifier': 'RandomForest', 'rf_max_depth': 30}. Best is trial 41 with value: 0.9733333333333333.

FrozenTrial(number=41, state=1, values=[0.9733333333333333], datetime_start=datetime.datetime(2025, 3, 14, 15, 2, 18, 365464), datetime_complete=datetime.datetime(2025, 3, 14, 15, 2, 18, 434743), params={'classifier': 'RandomForest', 'rf_max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'classifier': CategoricalDistribution(choices=('RandomForest',)), 'rf_max_depth': IntDistribution(high=32, log=True, low=2, step=1)}, trial_id=41, value=None)

In [28]:
df=svc.trials_dataframe()
df.sort_values(by=["value"],ascending=False).head(10)

,number,value,datetime_start,datetime_complete,duration,params_classifier,params_svc_c,state
106,106,0.986667,2025-03-14 15:02:14.329195,2025-03-14 15:02:14.345512,0 days 00:00:00.016317,SVC,3.951731,COMPLETE
111,111,0.986667,2025-03-14 15:02:14.421097,2025-03-14 15:02:14.438478,0 days 00:00:00.017381,SVC,3.743662,COMPLETE
114,114,0.986667,2025-03-14 15:02:14.474430,2025-03-14 15:02:14.492760,0 days 00:00:00.018330,SVC,4.835897,COMPLETE
101,101,0.986667,2025-03-14 15:02:14.241164,2025-03-14 15:02:14.257887,0 days 00:00:00.016723,SVC,3.703930,COMPLETE
102,102,0.986667,2025-03-14 15:02:14.258674,2025-03-14 15:02:14.275214,0 days 00:00:00.016540,SVC,4.067043,COMPLETE
100,100,0.986667,2025-03-14 15:02:14.223300,2025-03-14 15:02:14.240532,0 days 00:00:00.017232,SVC,4.434880,COMPLETE
82,82,0.986667,2025-03-14 15:02:13.904777,2025-03-14 15:02:13.921580,0 days 00:00:00.016803,SVC,3.766519,COMPLETE
85,85,0.986667,2025-03-14 15:02:13.957060,2025-03-14 15:02:13.974011,0 days 00:00:00.016951,SVC,3.822915,COMPLETE
138,138,0.986667,2025-03-14 15:02:14.907524,2025-03-14 15:02:14.924352,0 days 00:00:00.016828,SVC,3.952961,COMPLETE
144,144,0.986667,2025-03-14 15:02:15.014391,2025-03-14 15:02:15.031238,0 days 00:00:00.016847,SVC,4.442436,COMPLETE

In [17]:
rf.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_classifier,params_rf_max_depth,state
0,0,0.960000,2025-03-14 15:02:16.184004,2025-03-14 15:02:16.289241,0 days 00:00:00.105237,RandomForest,2,COMPLETE
1,1,0.953333,2025-03-14 15:02:16.289978,2025-03-14 15:02:16.335514,0 days 00:00:00.045536,RandomForest,8,COMPLETE
2,2,0.953333,2025-03-14 15:02:16.336156,2025-03-14 15:02:16.394323,0 days 00:00:00.058167,RandomForest,12,COMPLETE
3,3,0.966667,2025-03-14 15:02:16.395583,2025-03-14 15:02:16.442531,0 days 00:00:00.046948,RandomForest,17,COMPLETE
4,4,0.966667,2025-03-14 15:02:16.443263,2025-03-14 15:02:16.489535,0 days 00:00:00.046272,RandomForest,4,COMPLETE
...,...,...,...,...,...,...,...,...
195,195,0.960000,2025-03-14 15:02:26.669739,2025-03-14 15:02:26.745184,0 days 00:00:00.075445,RandomForest,4,COMPLETE
196,196,0.960000,2025-03-14 15:02:26.745977,2025-03-14 15:02:26.796563,0 days 00:00:00.050586,RandomForest,8,COMPLETE
197,197,0.966667,2025-03-14 15:02:26.797365,2025-03-14 15:02:26.847550,0 days 00:00:00.050185,RandomForest,23,COMPLETE
198,198,0.966667,2025-03-14 15:02:26.849046,2025-03-14 15:02:26.900204,0 days 00:00:00.051158,RandomForest,29,COMPLETE
199,199,0.960000,2025-03-14 15:02:26.901183,2025-03-14 15:02:26.951499,0 days 00:00:00.050316,RandomForest,5,COMPLETE